version: "3"

env:
  JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home
  TASK_X_REMOTE_TASKFILES: "1"

vars:
  SDK_PATH: ~/Library/Android/sdk/build-tools/36.1.0
  APP_NAME: meld

includes:
  android-common:
    # taskfile: /Users/jhot/projects/misc/taskfiles/android.yaml
    taskfile: https://raw.githubusercontent.com/jhot21/taskfiles/main/android.yaml
    flatten: true
